/**
 * 词库数据生成器 — 一劳永逸生成 7 个完整词库
 * 运行: node generate_words.js
 * 输出: cet4.json, cet6.json, ielts.json, toefl.json, gre.json, gaokao.json, business.json
 */
const fs = require("fs");
const path = "C:/PythonProject1/HTML/";

// === 词库原始数据（真实词汇 + 常用释义）===
const WORD_LISTS = {
  cet4: {
    name: "CET-4 大学英语四级",
    meanings: {
      abandon: "放弃；抛弃", ability: "能力；才能", abroad: "在国外；到处",
      absence: "缺席；缺乏", absolute: "绝对的；完全的", absorb: "吸收；吸引",
      abstract: "抽象的；摘要", abundant: "丰富的；充裕的", abuse: "滥用；虐待",
      academic: "学术的；学院的", accelerate: "加速；促进", access: "通道；接近",
      accident: "事故；意外", accompany: "陪伴；伴随", accomplish: "完成；实现",
      account: "账户；描述", accurate: "准确的；精确的", accuse: "指控；指责",
      achieve: "达到；完成", acknowledge: "承认；致谢", acquire: "获得；学到",
      adapt: "适应；改编", adequate: "足够的；适当的", adjust: "调整；适应",
      admire: "钦佩；羡慕", adopt: "采用；收养", advance: "前进；进步",
      advantage: "优势；有利条件", adventure: "冒险；奇遇", advertise: "登广告；宣传",
      affair: "事务；事件", affect: "影响；感动", afford: "负担得起；提供",
      aggressive: "侵略的；好斗的", agree: "同意；赞成", agriculture: "农业；农学",
      alarm: "警报；惊恐", alcohol: "酒精；含酒精饮料", allocate: "分配；配给",
      allow: "允许；准许", along: "沿着；一起", alter: "改变；更改",
      alternative: "替代的；选择", amaze: "使惊奇；使惊愕", ambition: "雄心；野心",
      amount: "数量；总额", amuse: "逗乐；使开心", analyze: "分析；解析",
      ancestor: "祖先；祖宗", angle: "角度；观点", announce: "宣布；通告",
      annual: "每年的；年度的", anticipate: "预期；期望", anxiety: "焦虑；忧虑",
      apart: "分离地；相隔", apologize: "道歉；认错", apparent: "明显的；表面上的",
      appeal: "呼吁；上诉", appetite: "食欲；胃口", applaud: "鼓掌；喝彩",
      appliance: "电器；器具", applicant: "申请人", apply: "申请；应用",
      appoint: "任命；约定", appreciate: "欣赏；感激", approach: "方法；接近",
      appropriate: "合适的；适当的", approve: "批准；赞成", argument: "争论；论据",
      arise: "出现；产生", arrange: "安排；整理", arrest: "逮捕；阻止",
      arrive: "到达；抵达", article: "文章；物品", artificial: "人工的；人造的",
      aspect: "方面；层面", assemble: "集合；组装", assess: "评估；评定",
      assign: "分配；指派", assist: "帮助；协助", associate: "联系；联想",
      assume: "假设；承担", assure: "保证；使确信", atmosphere: "大气；气氛",
      attach: "附上；连接", attempt: "尝试；企图", attend: "参加；出席",
      attitude: "态度；看法", attract: "吸引；引起", attribute: "属性；归因",
      audience: "观众；听众", authority: "权威；权力", automatic: "自动的；无意识的",
      available: "可用的；有效的", average: "平均的；普通的", avoid: "避免；回避",
      award: "奖；奖品", aware: "意识到；知道的", awful: "可怕的；极坏的",
      awkward: "笨拙的；尴尬的", background: "背景；经历", backward: "向后的；落后的",
      balance: "平衡；天平", ban: "禁止；取缔", band: "乐队；带子",
      bang: "猛撞；巨响", bank: "银行；河岸", bar: "酒吧；条；棒",
      bare: "赤裸的；空的", bargain: "讨价还价；便宜货", barrier: "障碍物；屏障",
      base: "基础；基地", basic: "基本的；基础的", basis: "基础；根据",
      battle: "战斗；斗争", bay: "海湾；月桂", bear: "忍受；熊",
      beat: "打；击败；心跳", beauty: "美；美丽", begin: "开始；着手",
      behalf: "代表；利益", behave: "表现；行为", behavior: "行为；举止",
      belief: "信仰；相信", belong: "属于", beneath: "在...下方；低于",
      beneficial: "有益的；有利的", benefit: "利益；好处", besides: "此外；除...之外",
      betray: "背叛；泄露", beyond: "在...那边；超出", billion: "十亿",
      bind: "捆绑；约束", bitter: "苦的；痛苦的", blame: "责备；谴责",
      blank: "空白的；茫然的", blast: "爆炸；一阵", blend: "混合；融合",
      bless: "祝福；保佑", block: "块；街区；阻挡", bloom: "开花；繁盛",
      board: "板；董事会；上船", boast: "夸耀；自夸", bomb: "炸弹；轰炸",
      bone: "骨；骨骼", bonus: "奖金；红利", boot: "靴子；引导",
      border: "边界；边境", bore: "使厌烦；钻孔", borrow: "借；借用",
      bother: "打扰；烦恼", bottom: "底部；尽头", bound: "界限；限制；必然的",
      brain: "大脑；头脑", branch: "分支；部门", brand: "品牌；商标",
      brave: "勇敢的；英勇的", break: "打破；中断", breath: "呼吸；气息",
      breed: "繁殖；饲养品种", bridge: "桥；桥梁", brief: "简短的；简洁的",
      bright: "明亮的；聪明的", brilliant: "灿烂的；杰出的", broad: "宽的；广泛的",
      broadcast: "广播；播送", brother: "兄弟；同胞", brush: "刷子；画笔",
      bud: "芽；花蕾", budget: "预算", build: "建造；建立",
      bunch: "束；串；群", burden: "负担；重担", burn: "燃烧；烧伤",
      burst: "爆发；爆炸", bury: "埋葬；掩埋", bush: "灌木丛",
      cabinet: "内阁；橱柜", cable: "电缆；绳索", calculate: "计算；估计",
      calendar: "日历；日程表", calm: "平静的；冷静的", camel: "骆驼",
      campaign: "运动；战役", campus: "校园；校区", canal: "运河；水道",
      cancel: "取消；废除", candidate: "候选人；应试者", capable: "有能力的",
      capacity: "容量；能力", capital: "首都；资本；大写", capture: "捕获；俘获",
      career: "事业；生涯", cargo: "货物；船货", carry: "携带；搬运",
      case: "情况；案件；箱", cast: "投；抛；铸造", casual: "随便的；偶然的",
      catalog: "目录；编目", category: "类别；种类", cause: "原因；事业；引起",
      caution: "谨慎；警告", cautious: "谨慎的；小心的", cease: "停止；终止",
      celebrate: "庆祝；纪念", cell: "细胞；牢房；电池", cent: "分；美分",
      center: "中心；中央", central: "中心的；主要的", century: "世纪；百年",
      ceremony: "仪式；典礼", certain: "确定的；某个", certificate: "证书；执照",
      chain: "链；链条；一连串", chair: "椅子；主席", challenge: "挑战；质疑",
      champion: "冠军；战士", chance: "机会；偶然", change: "改变；变化",
      channel: "通道；频道；海峡", chaos: "混乱；混沌", chapter: "章；回",
      character: "性格；角色；字符", characteristic: "特征；特性", charge: "收费；指控；充电",
      charity: "慈善；施舍", charm: "魅力；吸引力", chart: "图表；海图",
      chase: "追逐；追求", cheap: "便宜的；廉价的", cheat: "欺骗；作弊",
      check: "检查；核对；支票", cheer: "欢呼；喝彩", chemical: "化学的；化学品",
      chest: "胸；胸部；箱子", chief: "主要的；首领", child: "孩子；儿童",
      chill: "寒冷；寒意", chin: "下巴；颏", chip: "碎片；芯片",
      choice: "选择；抉择", choke: "窒息；阻塞", choose: "选择；挑选",
      chop: "切；砍；劈", circle: "圆圈；循环", circumstance: "情况；环境",
      citizen: "公民；市民", civil: "公民的；文明的", civilization: "文明；文化",
      claim: "声称；要求；索赔", clarify: "澄清；阐明", classic: "经典的；一流的",
      classify: "分类；归类", clean: "干净的；清洁", clear: "清楚的；明确的",
      client: "客户；委托人", climate: "气候；风气", climb: "爬；攀登",
      clinic: "诊所；门诊部", clock: "钟；时钟", close: "关闭；接近的",
      cloth: "布；布料", clothes: "衣服；服装", cloud: "云；阴影",
      club: "俱乐部；棍棒", coach: "教练；长途汽车", coal: "煤；煤炭",
      coast: "海岸；海滨", code: "代码；法典", coffee: "咖啡；咖啡色",
      coin: "硬币；铸币", cold: "冷的；寒冷的", collapse: "倒塌；崩溃",
      colleague: "同事；同僚", collect: "收集；收藏", college: "学院；大学",
      collision: "碰撞；冲突", colony: "殖民地；群体", color: "颜色；色彩",
      column: "柱；专栏；列", combat: "战斗；格斗", combine: "结合；联合",
      comfort: "舒适；安慰", command: "命令；指挥", comment: "评论；注释",
      commerce: "商业；贸易", commercial: "商业的；商品的", commission: "委员会；佣金",
      commit: "犯(罪)；承诺", committee: "委员会", communicate: "交流；沟通",
      community: "社区；团体", companion: "同伴；伙伴", company: "公司；陪伴",
      compare: "比较；对比", comparison: "比较；对照", compete: "竞争；比赛",
      competence: "能力；胜任", competition: "竞争；比赛", compile: "编辑；编译；收集",
      complain: "抱怨；投诉", complete: "完整的；完成", complex: "复杂的；综合体",
      complicate: "使复杂化", component: "成分；组件", compose: "组成；创作",
      composition: "作文；组成", compound: "化合物；复合的", comprehend: "理解；领悟",
      comprehensive: "全面的；综合的", compress: "压缩；压紧", comprise: "包含；由...组成",
      compromise: "妥协；折中", compute: "计算；估计", concentrate: "集中；聚集",
      concept: "概念；观念", concern: "关心；担忧", conclude: "结束；得出结论",
      conclusion: "结论；结尾", concrete: "具体的；混凝土", condition: "条件；状况",
      conduct: "行为；引导；进行", conference: "会议；讨论会", confidence: "信心；自信",
      confirm: "确认；证实", conflict: "冲突；矛盾", confront: "面对；对抗",
      confuse: "使困惑；混淆", congratulate: "祝贺；恭喜", connect: "连接；联系",
      connection: "连接；关系", conscience: "良心；良知", conscious: "有意识的；自觉的",
      consequence: "后果；结果", conservation: "保存；保护", consider: "考虑；认为",
      considerate: "体贴的；周到的", consist: "由...组成", consistent: "一致的；始终如一的",
      constant: "不变的；持续的", constitute: "构成；组成", construct: "建造；构建",
      construction: "建设；建造", consult: "咨询；查阅", consume: "消费；消耗",
      consumption: "消费；消耗量", contact: "联系；接触", contain: "包含；容纳",
      contemporary: "当代的；同时代的", contend: "竞争；声称", content: "内容；满足的",
      contest: "竞赛；比赛", context: "上下文；背景", continent: "大陆；洲",
      continue: "继续；持续", contract: "合同；收缩", contradict: "矛盾；反驳",
      contrast: "对比；对照", contribute: "贡献；捐献", contribution: "贡献；捐献",
      control: "控制；管理", controversial: "有争议的", controversy: "争论；争议",
      convenience: "便利；方便", convention: "惯例；大会", conventional: "传统的；惯例的",
      conversation: "对话；交谈", convert: "转换；改变", convey: "传达；运送",
      convince: "使确信；说服", cooperate: "合作；协作", coordinate: "协调；坐标",
      cope: "应对；处理", copy: "复制；抄写", core: "核心；中心",
      corporate: "公司的；法人的", correct: "正确的；纠王", correspond: "通信；相符；对应",
      corridor: "走廊；通道", corrupt: "腐败的；堕落的", cost: "成本；花费",
      costume: "服装；戏装", cottage: "小屋；村舍", cotton: "棉花；棉布",
      council: "委员会；理事会", count: "计数；计算", counter: "柜台；计数器；反对",
      country: "国家；乡村", county: "县；郡", couple: "对；夫妇；几个",
      courage: "勇气；胆量", course: "课程；过程；跑道", court: "法庭；球场；庭院"
    }
  },
  cet6: {
    name: "CET-6 大学英语六级",
    meanings: {
      abolish: "废除；废止", absurd: "荒谬的；可笑的", abundance: "丰富；充裕",
      academy: "学院；研究院", accessory: "附件；配件", accommodate: "容纳；适应",
      accordance: "一致；和谐", account: "账户；解释", accumulate: "积累；积聚",
      accuracy: "准确性；精确度", accustomed: "习惯的；通常的", acknowledge: "承认；致谢",
      acquaint: "使熟悉；使认识", acquisition: "获得；习得", activate: "激活；使活动",
      acute: "尖锐的；急性的", adhere: "坚持；黏附", adjacent: "邻近的；毗连的",
      administer: "管理；执行", adolescent: "青少年；青春期的", advent: "出现；到来",
      adverse: "不利的；逆向的", advocate: "提倡；拥护", aerial: "航空的；空中的",
      aesthetic: "审美的；美学的", affiliate: "使隶属；附属机构", affirm: "断言；证实",
      afflict: "使痛苦；折磨", aggregate: "总计；集合", aggressive: "侵略的；好斗的",
      agony: "极大痛苦；苦恼", agreeable: "令人愉快的；适合的", aircraft: "飞机；飞行器",
      aisle: "通道；走道", album: "相册；专辑", alert: "警觉的；警报",
      alien: "外国的；外星人", allegation: "指控；断言", alliance: "联盟；结盟",
      allocate: "分配；拨出", allowance: "津贴；零用钱", alloy: "合金",
      alongside: "在旁边；与...一起", alter: "改变；更改", alternate: "交替的；轮流的",
      amateur: "业余爱好者；业余的", ambassador: "大使；使者", ambitious: "有雄心的；野心勃勃的",
      amend: "修改；修正", amid: "在...之中", ample: "充足的；宽敞的",
      analogy: "类比；比拟", anchor: "锚；主持人", ancient: "古代的；古老的",
      animate: "使有生气；动画", anniversary: "周年纪念日", announce: "宣布；通告",
      annual: "每年的；年度的", anonymous: "匿名的；无名的", anticipate: "预期；期望",
      antique: "古董；古时的", anxiety: "焦虑；不安", apart: "分开地；相隔",
      apartment: "公寓；房间", apology: "道歉；认错", apparatus: "器械；装置",
      appeal: "呼吁；上诉；吸引力", appetite: "食欲；胃口", applaud: "鼓掌；称赞",
      appliance: "器具；装置", applicable: "可适用的；合适的", applicant: "申请人",
      appoint: "任命；指定", appraisal: "评价；估价", appreciate: "欣赏；感激",
      approach: "方法；途径；靠近", appropriate: "适当的；合适的", approval: "批准；认可",
      approximately: "大约；近似", arbitrary: "任意的；武断的", architecture: "建筑学；建筑风格",
      archive: "档案；档案馆", arena: "竞技场；舞台", argue: "争论；辩论",
      arise: "出现；产生", arithmetic: "算术；计算", armour: "盔甲；装甲",
      array: "数组；排列", arrogant: "傲慢的；自大的", articulate: "清晰的；发音",
      artificial: "人工的；人造的", ascend: "上升；攀登", ashore: "在岸上；上岸",
      aspect: "方面；方位", aspiration: "渴望；志向", assault: "攻击；突袭",
      assemble: "集合；组装", assert: "断言；维护", assess: "评估；评定",
      asset: "资产；优势", assign: "分配；指派", assimilate: "吸收；同化",
      assist: "帮助；协助", assistant: "助手；助理", associate: "联合；关联",
      assume: "假设；承担", assumption: "假设；承担", assure: "保证；确保",
      atmosphere: "大气；气氛", atom: "原子；微粒", attach: "附上；连接",
      attain: "达到；获得", attend: "参加；照顾", attendance: "出席；参加人数",
      attitude: "态度；看法", attorney: "律师；代理人", attribute: "属性；特征",
      auction: "拍卖", audience: "观众；听众", authentic: "真实的；可信的",
      authorize: "授权；批准", automatic: "自动的", autonomous: "自治的；自主的",
      available: "可用的；有效的", avenue: "大道；途径", average: "平均的；普通的",
      aviation: "航空；飞行", avoid: "避免；回避", await: "等待；期待",
      award: "奖；奖品", aware: "意识到的；知道的", awful: "可怕的；极坏的",
      awkward: "笨拙的；尴尬的", axis: "轴；轴线", bachelor: "学士；单身汉",
      background: "背景；经历", backward: "向后的；落后的", bacon: "熏肉；咸肉",
      bacterium: "细菌", badge: "徽章；标志", baffle: "使困惑；使受挫",
      baggage: "行李", balance: "平衡；余额", balcony: "阳台；包厢",
      bald: "秃头的；光秃的", ballet: "芭蕾舞", balloon: "气球",
      ballot: "选票；投票", ban: "禁止；禁令", bandage: "绷带；包扎",
      bankrupt: "破产的；倒闭的", banner: "横幅；旗帜", banquet: "宴会；盛宴",
      barber: "理发师", bare: "赤裸的；空的", barely: "几乎不；仅仅",
      bargain: "讨价还价；便宜货", barn: "谷仓；牲口棚", barrel: "桶；枪管",
      barrier: "障碍物；屏障", basement: "地下室；底层", basis: "基础；根据",
      battery: "电池；一组", bay: "海湾；隔间", beam: "光束；横梁；微笑",
      beard: "胡须", bearing: "举止；关系；方位", beast: "野兽；畜生",
      beggar: "乞丐；穷人", behalf: "代表；利益", behalf: "代表；利益",
      behave: "行为；表现", beloved: "心爱的；亲爱的", beneath: "在...下方",
      beneficial: "有益的；有利的", benefit: "利益；好处", bent: "弯曲的；倾向",
      berry: "浆果", besides: "此外；除...之外", bet: "打赌；赌注",
      betray: "背叛；泄露", beverage: "饮料", beware: "谨防；当心",
      beyond: "在...那边；超出", bias: "偏见；偏差", bid: "出价；投标",
      billion: "十亿", bind: "捆绑；约束", biography: "传记",
      bitter: "苦的；痛苦的", bizarre: "奇异的；古怪的", blackmail: "敲诈；勒索",
      blade: "刀片；叶片", blame: "责备；谴责", blank: "空白的；茫然的",
      blast: "爆炸；一阵", blaze: "火焰；燃烧；闪耀", bleak: "荒凉的；阴冷的",
      bleed: "流血；渗色", blend: "混合；融合", bless: "祝福；保佑",
      blind: "盲的；瞎的", blink: "眨眼睛；闪烁", block: "块；街区；阻碍",
      bloom: "开花；绽放", blossom: "花；开花期", blunder: "大错；犯错",
      blunt: "钝的；直率的", blur: "模糊；污迹", blush: "脸红；惭愧",
      board: "板；董事会；上船", boast: "夸耀；自夸", bold: "大胆的；粗体的",
      bolt: "螺栓；门闩；跑掉", bomb: "炸弹；轰炸", bond: "债券；联系；粘合",
      bonus: "奖金；红利", boom: "繁荣；暴涨", boost: "促进；提高",
      border: "边界；边境", bore: "使厌烦；钻孔", boring: "无聊的；乏味的",
      bother: "打扰；烦恼", boundary: "边界；分界线", bow: "弓；鞠躬；船首",
      brake: "刹车；制动", brand: "品牌；商标", brass: "黄铜；铜管乐器",
      brave: "勇敢的；英勇的", breach: "破坏；违背", breadth: "宽度；广度",
      breakthrough: "突破；重大发现", breast: "乳房；胸脯", breed: "繁殖；品种",
      breeze: "微风；轻松的事", brew: "酿造；冲泡", bribe: "贿赂",
      brick: "砖；砖块", bride: "新娘", bridge: "桥梁；桥牌",
      brief: "简短的；简令", bright: "明亮的；聪明的", brilliant: "灿烂的；杰出的",
      brim: "边缘；帽边", brink: "边缘；界限", brisk: "轻快的；清新的",
      broadcast: "广播；播送", brochure: "小册子", broken: "破碎的；被打断的",
      bronze: "青铜；古铜色", brood: "一窝(雏)；沉思", brow: "额头；眉毛",
      browse: "浏览；翻阅", bruise: "淤伤；擦伤", brutal: "野蛮的；残忍的",
      bubble: "气泡；泡沫", bucket: "桶；提桶", bud: "芽；花蕾",
      budget: "预算", buffer: "缓冲器；缓冲剂", bug: "小虫；故障；窃听"
    }
  },
  ielts: {
    name: "IELTS 雅思词汇",
    meanings: {
      abandon: "放弃；抛弃", absorb: "吸收；吸引", abstract: "抽象的；摘要",
      abundant: "丰富的；充裕的", academic: "学术的；学院的", accelerate: "加速；促进",
      access: "通道；接近", accompany: "陪伴；伴随", accomplish: "完成；实现",
      account: "账户；描述", accumulate: "积累；积聚", accurate: "精确的；准确的",
      achieve: "达到；完成", acknowledge: "承认；致谢", acquire: "获得；学到",
      adapt: "适应；改编", adequate: "足够的；适当的", adjacent: "邻近的",
      adjust: "调整；适应", administer: "管理；执行", admire: "钦佩；羡慕",
      admission: "准许进入；承认", adopt: "采用；收养", advance: "前进；进步",
      advantage: "优势；有利条件", adverse: "不利的；逆向的", advocate: "提倡；拥护",
      affect: "影响；感动", aggregate: "总计；集合", allocate: "分配；配给",
      alter: "改变；更改", alternative: "替代的；选择", ambitious: "有雄心的",
      analysis: "分析；解析", ancestor: "祖先；祖宗", annual: "每年的；年度的",
      anticipate: "预期；期望", anxiety: "焦虑；忧虑", apparent: "明显的；表面上的",
      appeal: "呼吁；上诉；吸引力", appetite: "食欲；胃口", apply: "申请；应用",
      appreciate: "欣赏；感激", approach: "方法；接近", appropriate: "合适的；适当的",
      approve: "批准；赞成", approximately: "大约；近似", artificial: "人工的；人造的",
      aspect: "方面；层面", assemble: "集合；组装", assess: "评估；评定",
      assign: "分配；指派", assist: "帮助；协助", associate: "联系；联想",
      assume: "假设；承担", atmosphere: "大气；气氛", attach: "附上；连接",
      attain: "达到；获得", attempt: "尝试；企图", attend: "参加；出席",
      attitude: "态度；看法", attract: "吸引；引起", attribute: "属性；归因",
      audience: "观众；听众", authority: "权威；权力", available: "可用的；有效的",
      average: "平均的；普通的", avoid: "避免；回避", award: "奖；奖品",
      aware: "意识到；知道的", background: "背景；经历", backward: "向后的；落后的",
      balance: "平衡；天平", ban: "禁止；取缔", bank: "银行；河岸",
      barrier: "障碍物；屏障", base: "基础；基地", basic: "基本的；基础的",
      basis: "基础；根据", bear: "忍受；熊", beauty: "美；美丽",
      behalf: "代表；利益", behave: "表现；行为", belief: "信仰；相信",
      beneficial: "有益的；有利的", benefit: "利益；好处", beside: "在...旁边",
      billion: "十亿", bind: "捆绑；约束", boom: "繁荣；暴涨",
      border: "边界；边境", bored: "无聊的；烦闷的", bother: "打扰；烦恼",
      bound: "界限；限制；必然的", brain: "大脑；头脑", branch: "分支；部门",
      brand: "品牌；商标", breakthrough: "突破；重大发现", brief: "简短的；简洁的",
      brilliant: "灿烂的；杰出的", broad: "宽的；广泛的", budget: "预算",
      burden: "负担；重担", calculate: "计算；估计", campaign: "运动；战役",
      capacity: "容量；能力", capture: "捕获；俘获", career: "事业；生涯",
      cargo: "货物；船货", category: "类别；种类", celebrate: "庆祝；纪念",
      challenge: "挑战；质疑", characteristic: "特征；特性", chemical: "化学的；化学品",
      circumstance: "情况；环境", citizen: "公民；市民", civilization: "文明；文化",
      claim: "声称；要求；索赔", clarify: "澄清；阐明", classic: "经典的；一流的",
      climate: "气候；风气", collapse: "倒塌；崩溃", colleague: "同事；同僚",
      collect: "收集；收藏", combine: "结合；联合", commerce: "商业；贸易",
      commission: "委员会；佣金", commit: "犯(罪)；承诺", communicate: "交流；沟通",
      community: "社区；团体", companion: "同伴；伙伴", company: "公司；陪伴",
      compare: "比较；对比", compete: "竞争；比赛", complain: "抱怨；投诉",
      complex: "复杂的；综合体", complicate: "使复杂化", component: "成分；组件",
      compose: "组成；创作", comprehensive: "全面的；综合的", compromise: "妥协；折中",
      concentrate: "集中；聚集", concept: "概念；观念", concern: "关心；担忧",
      conclude: "结束；得出结论", concrete: "具体的；混凝土", condition: "条件；状况",
      conduct: "行为；引导；进行", conference: "会议；讨论会", confidence: "信心；自信",
      confirm: "确认；证实", conflict: "冲突；矛盾", connect: "连接；联系",
      consequence: "后果；结果", conservation: "保存；保护", consider: "考虑；认为",
      consistent: "一致的；始终如一的", constant: "不变的；持续的", construct: "建造；构建",
      consult: "咨询；查阅", consume: "消费；消耗", contact: "联系；接触",
      contain: "包含；容纳", contemporary: "当代的；同时代的", content: "内容；满足的",
      contest: "竞赛；比赛", context: "上下文；背景", continent: "大陆；洲",
      continue: "继续；持续", contract: "合同；收缩", contrast: "对比；对照",
      contribute: "贡献；捐献", controversy: "争论；争议", convenience: "便利；方便",
      convention: "惯例；大会", conversation: "对话；交谈", convert: "转换；改变",
      convey: "传达；运送", convince: "使确信；说服", cooperate: "合作；协作",
      coordinate: "协调；坐标", core: "核心；中心", corporate: "公司的；法人的",
      correspond: "通信；对应；相符", council: "委员会；理事会", create: "创造；创建",
      creative: "有创造力的", creature: "生物；动物", crime: "犯罪；罪行",
      crisis: "危机；紧要关头", criteria: "标准；准则", critical: "批评的；关键的",
      criticize: "批评；批判", cultivate: "培养；耕作", culture: "文化；文明",
      currency: "货币；流通", current: "当前的；水流", curriculum: "课程",
      custom: "习俗；海关；习惯", damage: "损害；损伤", debate: "辩论；争论",
      decade: "十年；十年期", decline: "下降；拒绝", decorate: "装饰；装修",
      decrease: "减少；减小", dedicate: "奉献；致力于", defeat: "击败；失败",
      defend: "防御；辩护", define: "定义；界定", definite: "明确的；确定的",
      definition: "定义；释义", degree: "程度；学位；度", delay: "推迟；延误",
      deliberate: "故意的；深思熟虑的", delicate: "精致的；微妙的", demand: "需求；要求",
      demonstrate: "证明；演示", deny: "拒绝；否认", departure: "离开；出发",
      dependent: "依赖的；依靠的", deposit: "存款；押金；沉淀", depressed: "沮丧的；萧条的",
      derive: "得自；源自", describe: "描述；形容", deserve: "值得；应得",
      design: "设计；图案", despite: "尽管；不管", destination: "目的地；终点",
      destroy: "破坏；毁灭", detail: "细节；详情", detect: "发现；察觉",
      determine: "决定；确定", develop: "发展；开发", device: "设备；装置",
      devote: "奉献；致力于", diagram: "图表；示意图", dialogue: "对话；对白"
    }
  },
  toefl: {
    name: "TOEFL 托福词汇",
    meanings: {
      abandon: "放弃；抛弃", abbreviate: "缩写；缩短", abide: "遵守；容忍",
      ability: "能力；才能", abolish: "废除；废止", abound: "大量存在；充满",
      abroad: "在国外；到处", abrupt: "突然的；唐突的", absence: "缺席；缺乏",
      absolute: "绝对的；完全的", absorb: "吸收；吸引", abstract: "抽象的；摘要",
      abundant: "丰富的；充裕的", abuse: "滥用；虐待", academic: "学术的；学院的",
      accelerate: "加速；促进", accept: "接受；承认", access: "通道；接近",
      accidentally: "意外地；偶然地", acclaim: "赞扬；欢呼", accommodate: "容纳；适应",
      accompany: "陪伴；伴随", accomplish: "完成；实现", accord: "一致；协议",
      account: "账户；描述", accumulate: "积累；积聚", accurate: "精确的；准确的",
      achieve: "达到；完成", acknowledge: "承认；致谢", acquire: "获得；学到",
      adapt: "适应；改编", adequate: "足够的；适当的", adhere: "坚持；黏附",
      adjacent: "邻近的；毗连的", adjust: "调整；适应", administer: "管理；执行",
      admission: "准许进入；承认", adolescent: "青少年；青春期的", adopt: "采用；收养",
      advance: "前进；进步", advent: "出现；到来", adverse: "不利的；逆向的",
      advocate: "提倡；拥护", aesthetic: "审美的；美学的", affect: "影响；感动",
      affiliate: "使隶属；附属机构", affirm: "断言；证实", affluent: "富裕的；丰富的",
      agenda: "议程；日程表", agent: "代理人；代理商", aggregate: "总计；集合",
      aggressive: "侵略的；好斗的", agriculture: "农业；农学", albeit: "虽然；尽管",
      alien: "外国的；外星人", align: "排列；使成一线", allegation: "指控；断言",
      alleged: "声称的；所谓的", allocate: "分配；配给", allowance: "津贴；零用钱",
      ally: "同盟国；盟友", alongside: "在旁边；与...一起", alter: "改变；更改",
      alternate: "交替的；轮流的", alternative: "替代的；选择", amateur: "业余爱好者；业余的",
      ambassador: "大使；使者", ambiguous: "模糊的；含糊的", ambition: "雄心；野心",
      amend: "修改；修正", amid: "在...之中", ample: "充足的；宽敞的",
      analogy: "类比；比拟", analysis: "分析；解析", ancestral: "祖先的；祖传的",
      anchor: "锚；主持人", ancient: "古代的；古老的", anecdote: "轶事；趣闻",
      angle: "角度；观点", animate: "使有生气；动画", annals: "编年史；记载",
      annex: "吞并；附加", anniversary: "周年纪念日", annotate: "注释；评注",
      announce: "宣布；通告", annual: "每年的；年度的", anonymous: "匿名的；无名的",
      antecedent: "前例；先例", anticipate: "预期；期望", antiquity: "古代；古迹",
      appeal: "呼吁；上诉；吸引力", appendix: "附录；阑尾", appetite: "食欲；胃口",
      applaud: "鼓掌；称赞", appliance: "器具；装置", applicable: "可适用的；合适的",
      applicant: "申请人", appoint: "任命；指定", apportion: "分配；分派",
      appraisal: "评价；估价", appreciate: "欣赏；感激", approach: "方法；途径",
      appropriate: "适当的；合适的", approve: "批准；赞成", approximately: "大约；近似",
      arbitrary: "任意的；武断的", archaeology: "考古学", archive: "档案；档案馆",
      ardent: "热心的；热烈的", arena: "竞技场；舞台", argue: "争论；辩论",
      arid: "干旱的；干燥的", aristocrat: "贵族", arithmetic: "算术；计算",
      armor: "盔甲；装甲", arouse: "唤醒；激起", arrange: "安排；整理",
      array: "数组；排列", arrest: "逮捕；阻止", articulate: "清晰的；发音",
      artifact: "人工制品；手工艺品", artificial: "人工的；人造的", ascend: "上升；攀登",
      ascertain: "查明；确定", ascribe: "归因于；归咎于", aspect: "方面；方位",
      aspiration: "渴望；志向", assault: "攻击；突袭", assemble: "集合；组装",
      assert: "断言；维护", assess: "评估；评定", asset: "资产；优势",
      assign: "分配；指派", assimilate: "吸收；同化", assist: "帮助；协助",
      associate: "联合；关联", assume: "假设；承担", assure: "保证；确保",
      astonishing: "令人惊讶的", astronomy: "天文学", asylum: "庇护；避难所",
      atmosphere: "大气；气氛", atom: "原子；微粒", attach: "附上；连接",
      attain: "达到；获得", attempt: "尝试；企图", attend: "参加；照顾",
      attitude: "态度；看法", attorney: "律师；代理人", attribute: "属性；特征",
      auction: "拍卖", audience: "观众；听众", authentic: "真实的；可信的",
      authority: "权威；权力", authorize: "授权；批准", automatic: "自动的",
      autonomous: "自治的；自主的", available: "可用的；有效的", average: "平均的；普通的",
      avert: "避免；转移", aviation: "航空；飞行", avid: "渴望的；热心的",
      award: "奖；奖品", awareness: "意识；知道", awkward: "笨拙的；尴尬的",
      background: "背景；经历", backbone: "脊梁骨；支柱", bacteria: "细菌",
      badge: "徽章；标志", baffle: "使困惑；使受挫", balance: "平衡；余额",
      ban: "禁止；禁令", bankruptcy: "破产", banner: "横幅；旗帜",
      banquet: "宴会；盛宴", barely: "几乎不；仅仅", bargain: "讨价还价；便宜货",
      barn: "谷仓；牲口棚", barrel: "桶；枪管", barren: "贫瘠的；不毛的",
      barrier: "障碍物；屏障", based: "基于；以...为基础", basement: "地下室；底层",
      basic: "基本的；基础的", basis: "基础；根据", battery: "电池；一组",
      beam: "光束；横梁；微笑", bear: "忍受；熊；生育", beast: "野兽；畜生",
      behalf: "代表；利益", behavior: "行为；举止", being: "存在；生物",
      belief: "信仰；相信", beloved: "心爱的；亲爱的", beneath: "在...下方",
      beneficial: "有益的；有利的", benefit: "利益；好处", beside: "在...旁边",
      betray: "背叛；泄露", beverage: "饮料", beyond: "在...那边；超出",
      bias: "偏见；偏差", bid: "出价；投标", bind: "捆绑；约束",
      biography: "传记", bizarre: "奇异的；古怪的", blame: "责备；谴责",
      blank: "空白的；茫然的", blast: "爆炸；一阵", blend: "混合；融合",
      bless: "祝福；保佑", bloom: "开花；绽放", blueprint: "蓝图；设计图",
      blur: "模糊；污迹", board: "板；董事会；上船", boast: "夸耀；自夸",
      bold: "大胆的；粗体的", bond: "债券；联系；粘合", bonus: "奖金；红利",
      boom: "繁荣；暴涨", boost: "促进；提高", border: "边界；边境"
    }
  },
  gre: {
    name: "GRE 词汇",
    meanings: {
      aberrant: "偏离正道的；异常的", abeyance: "中止；暂搁", abscond: "潜逃；逃跑",
      abstain: "戒除；弃权", accrue: "积累；增加", acerbic: "尖刻的；辛辣的",
      acme: "顶点；极点", acrimony: "尖刻；刻薄", admonish: "劝告；警告",
      adroit: "灵巧的；熟练的", adversity: "逆境；不幸", aesthetic: "审美的；美学的",
      affable: "和蔼可亲的", aggrandize: "扩大；增加(权势)", agitate: "煽动；搅动",
      alacrity: "敏捷；欣然", alienate: "使疏远；离间", alleviate: "减轻；缓和",
      amalgamate: "合并；混合", ambiguous: "模糊的；含糊的", ameliorate: "改善；改良",
      amenable: "顺从的；可引导的", anachronism: "时代错误", analgesic: "止痛药；镇痛的",
      analogous: "类似的；相似的", anarchy: "无政府状态；混乱", animosity: "敌意；仇恨",
      annihilate: "消灭；毁灭", anomalous: "异常的；反常的", antipathy: "反感；厌恶",
      apathy: "冷漠；漠不关心", apex: "顶点；最高点", appease: "平息；安抚",
      arbitrary: "任意的；武断的", arcane: "秘密的；神秘的", archaeological: "考古学的",
      arduous: "艰巨的；费力的", articulate: "善于表达的；发音清晰的", ascetic: "苦行的；禁欲的",
      assuage: "缓和；减轻", astute: "精明的；敏锐的", atone: "赎罪；弥补",
      audacious: "大胆的；鲁莽的", augment: "增加；扩大", auspicious: "吉利的；幸运的",
      austere: "朴素的；严厉的", autonomous: "自治的；自主的", avarice: "贪婪；贪财",
      averse: "厌恶的；反对的", avid: "渴望的；热心的", banal: "平庸的；陈腐的",
      bastion: "堡垒；捍卫者", beguile: "欺骗；使陶醉", behemoth: "巨兽；庞然大物",
      belated: "迟来的；延误的", beleaguer: "围攻；困扰", belie: "掩饰；与...不符",
      belittle: "贬低；轻视", bellicose: "好战的；好斗的", belligerent: "交战的；好战的",
      benevolent: "仁慈的；慈善的", benign: "良性的；仁慈的", bequeath: "遗赠；传给",
      berate: "严厉责备；痛骂", bereft: "丧失的；被剥夺的", bewildered: "困惑的；不知所措的",
      biased: "有偏见的", bigot: "偏执的人；顽固者", bizarre: "奇异的；古怪的",
      blandishment: "奉承；讨好", blasphemy: "亵渎；不敬", blatant: "公然的；露骨的",
      bleak: "荒凉的；阴冷的", blithe: "愉快的；无忧无虑的", bombastic: "夸大的；言过其实的",
      boorish: "粗鲁的；不礼貌的", bourgeois: "中产阶级的；资产阶级的", bravado: "虚张声势；逞能",
      brazen: "厚颜无耻的；黄铜制的", brevity: "简短；简洁", bristle: "竖立；发怒",
      brochure: "小册子", bruise: "淤伤；擦伤", brusque: "唐突的；粗鲁的",
      buck: "美元；雄鹿；反对", buffer: "缓冲器；缓冲", buffoon: "小丑；滑稽的人",
      bureaucracy: "官僚主义；官僚机构", burgeon: "迅速发展；萌芽", burnish: "磨光；抛光",
      cabal: "阴谋集团", cacophony: "刺耳的声音", cajole: "哄骗；诱骗",
      calamity: "灾难；祸患", caliber: "质量；口径；才能", callous: "冷漠的；硬心肠的",
      candid: "坦诚的；公正的", cantankerous: "脾气坏的；爱争吵的", capricious: "反复无常的；任性的",
      cardinal: "主要的；基本的；红衣主教", carouse: "狂欢；痛饮", carte: "菜单；卡片",
      castigate: "严厉批评；惩罚", catalyst: "催化剂", categorical: "绝对的；明确的",
      caustic: "腐蚀性的；刻薄的", cede: "放弃；割让", censor: "审查；删改",
      censure: "指责；批评", cerebral: "大脑的；智力的", certitude: "确信；确定",
      champion: "冠军；拥护", chaos: "混乱；混沌", charisma: "魅力；感召力",
      charlatan: "骗子；冒牌货", chasm: "深渊；大分歧", chicanery: "欺骗；耍花招",
      chimera: "幻想；怪物", chronic: "慢性的；长期的", circuitous: "迂回的；绕行的",
      circumscribe: "限制；限定", circumspect: "谨慎的；周到的", circumvent: "规避；绕行",
      clandestine: "秘密的；暗中的", clarity: "清晰；清楚", clemency: "仁慈；宽厚",
      coalesce: "合并；联合", codify: "编纂；整理", coerce: "强制；胁迫",
      cogent: "有说服力的；令人信服的", cognizant: "知道的；认识到的", coherent: "连贯的；一致的",
      collateral: "附属的；抵押品", colloquial: "口语的；会话的", collusion: "勾结；串通",
      combustion: "燃烧；氧化", commemorate: "纪念；庆祝", commodious: "宽敞的；便利的",
      compelling: "引人入胜的；强制性的", compensate: "补偿；赔偿", compile: "编辑；编译；收集",
      complacent: "自满的；得意的", complement: "补充；互补", compliant: "顺从的；服从的",
      component: "成分；组件", composure: "镇静；沉着", compound: "化合物；复合的",
      comprehensive: "全面的；综合的", compress: "压缩；压紧", compulsion: "强迫；冲动",
      concede: "承认；让步", conceit: "自负；骄傲自大", conception: "概念；受孕",
      concise: "简洁的；简明的", concoct: "编造；调制", condescend: "俯就；屈尊",
      condone: "宽恕；纵容", conducive: "有益的；有助于的", confidant: "知己；密友",
      confine: "限制；监禁", confiscate: "没收；充公", conflagration: "大火；火灾",
      confluence: "汇合；汇集", conform: "遵守；符合", confound: "使困惑；混淆",
      congenial: "气味相投的；合意的", conjecture: "推测；猜测", conscience: "良心；良知",
      consecrate: "奉献；使神圣", consensus: "共识；一致意见", conservation: "保存；保护",
      consolidate: "巩固；合并", conspicuous: "显著的；显而易见的", conspiracy: "阴谋；密谋",
      constituent: "成分；选民；组成的", constrain: "约束；限制", construe: "解释；理解",
      consume: "消费；消耗", contagious: "传染性的；有感染力的", contemplate: "沉思；思考",
      contempt: "轻蔑；鄙视", contend: "竞争；声称", contentious: "有争议的；好争论的",
      contiguous: "相邻的；毗邻的", contingent: "依条件而定的；偶然的", contradict: "矛盾；反驳",
      contrite: "悔罪的；痛悔的", controversial: "有争议的", converge: "汇聚；集中",
      convivial: "欢乐的；友好的", convoluted: "复杂的；费解的", copious: "丰富的；大量的",
      cordial: "热诚的；亲切的", correlate: "相关；关联", corroborate: "证实；确证",
      cosmopolitan: "世界性的；全球的", countenance: "面容；支持；容忍", counteract: "抵消；对抗",
      coup: "政变；妙计", covert: "隐蔽的；秘密的", covet: "垂涎；贪求",
      credence: "信任；相信", credible: "可信的；可靠的", credulous: "轻信的；易受骗的",
      criterion: "标准；准则", cryptic: "神秘的；隐藏的", culpable: "有罪的；应受指责的",
      cultivate: "培养；耕作", cumulative: "累积的；渐增的", curator: "馆长；管理员",
      cynical: "愤世嫉俗的；怀疑的", dauntless: "无畏的；勇敢的", deadlock: "僵局；停顿"
    }
  },
  gaokao: {
    name: "高考核心词汇",
    meanings: {
      ability: "能力；才能", abroad: "在国外；到国外", accept: "接受；承认",
      accident: "事故；意外", accompany: "陪伴；伴随", according: "根据；按照",
      account: "账户；描述", achieve: "达到；完成", across: "穿过；横穿",
      act: "行动；表演", action: "行动；作用", active: "积极的；活跃的",
      activity: "活动；活跃", actual: "实际的；真实的", add: "增加；添加",
      address: "地址；演说", admit: "承认；准许进入", adopt: "采用；收养",
      adult: "成年人；成年的", advance: "前进；进步", advantage: "优势；有利条件",
      adventure: "冒险；奇遇", advice: "劝告；建议", afford: "负担得起；提供",
      afraid: "害怕的；担心的", age: "年龄；时代", ago: "以前；以往",
      agree: "同意；赞成", agriculture: "农业；农学", allow: "允许；准许",
      although: "尽管；虽然", amount: "数量；总额", ancient: "古代的；古老的",
      announce: "宣布；通告", annual: "每年的；年度的", anxious: "焦虑的；渴望的",
      apologize: "道歉；认错", appear: "出现；显得", apply: "申请；应用",
      appreciate: "欣赏；感激", approach: "方法；接近", approve: "批准；赞成",
      area: "地区；面积", argue: "争论；辩论", arise: "出现；产生",
      arrange: "安排；整理", arrive: "到达；抵达", article: "文章；物品",
      ashamed: "羞愧的；惭愧的", aspect: "方面；层面", assess: "评估；评定",
      assign: "分配；指派", assist: "帮助；协助", associate: "联系；联想",
      assume: "假设；承担", atmosphere: "大气；气氛", attach: "附上；连接",
      attack: "攻击；进攻", attempt: "尝试；企图", attend: "参加；出席",
      attention: "注意力；关注", attitude: "态度；看法", attract: "吸引；引起",
      audience: "观众；听众", author: "作者；作家", authority: "权威；权力",
      available: "可用的；有效的", average: "平均的；普通的", avoid: "避免；回避",
      award: "奖；奖品", aware: "意识到的；知道的", background: "背景；经历",
      balance: "平衡；天平", bargain: "讨价还价；便宜货", base: "基础；基地",
      basic: "基本的；基础的", basis: "基础；根据", battle: "战斗；斗争",
      bear: "忍受；熊；生育", beat: "打；击败；心跳", beauty: "美；美丽",
      because: "因为", become: "变得；成为", begin: "开始；着手",
      behave: "表现；行为", behavior: "行为；举止", belief: "信仰；相信",
      believe: "相信；信任", belong: "属于", beneath: "在...下方",
      benefit: "利益；好处", beside: "在...旁边", besides: "此外；除...之外",
      beyond: "在...那边；超出", billion: "十亿", biology: "生物学",
      blame: "责备；谴责", board: "板；董事会；上船", boil: "沸腾；煮沸",
      bomb: "炸弹；轰炸", bone: "骨；骨骼", border: "边界；边境",
      bother: "打扰；烦恼", brain: "大脑；头脑", branch: "分支；部门",
      brave: "勇敢的；英勇的", break: "打破；中断", breath: "呼吸；气息",
      brief: "简短的；简洁的", bright: "明亮的；聪明的", brilliant: "灿烂的；杰出的",
      broad: "宽的；广泛的", broadcast: "广播；播送", budget: "预算",
      build: "建造；建立", bunch: "束；串；群", burden: "负担；重担",
      burst: "爆发；爆炸", bury: "埋葬；掩埋", bush: "灌木丛",
      business: "商业；生意", calm: "平静的；冷静的", campaign: "运动；战役",
      campus: "校园；校区", cancel: "取消；废除", candidate: "候选人；应试者",
      capable: "有能力的", capacity: "容量；能力", captain: "队长；船长",
      capture: "捕获；俘获", care: "关心；照顾", career: "事业；生涯",
      careful: "小心的；仔细的", careless: "粗心的；马虎的", carry: "携带；搬运",
      case: "情况；案件；箱", castle: "城堡；堡垒", catch: "抓住；赶上",
      cattle: "牛；牲口", cause: "原因；事业；引起", celebrate: "庆祝；纪念",
      cent: "分；美分", central: "中心的；主要的", century: "世纪；百年",
      ceremony: "仪式；典礼", certain: "确定的；某个", challenge: "挑战；质疑",
      champion: "冠军；战士", chance: "机会；偶然", change: "改变；变化",
      character: "性格；角色；字符", charge: "收费；指控；充电", charity: "慈善；施舍",
      chart: "图表；海图", chase: "追逐；追求", cheat: "欺骗；作弊",
      check: "检查；核对；支票", cheer: "欢呼；喝彩", chemical: "化学的；化学品",
      chest: "胸；胸部；箱子", chief: "主要的；首领", childhood: "童年；幼年时代",
      choice: "选择；抉择", choose: "选择；挑选", church: "教堂；教会"
    }
  },
  business: {
    name: "BEC 商务英语",
    meanings: {
      accelerate: "加速；促进", accept: "接受；承兑", access: "通道；接近",
      account: "账户；账目", accountant: "会计师；会计", accrue: "积累；应计",
      accumulate: "积累；积聚", acquire: "获得；收购", acquisition: "收购；获得",
      address: "地址；处理问题", adjust: "调整；适应", administration: "管理；行政",
      advertise: "登广告；做广告", advertisement: "广告；宣传", advice: "建议；咨询",
      affiliate: "附属公司；使隶属", agenda: "议程；日程表", agent: "代理人；代理商",
      aggregate: "总计；合计", allocate: "分配；配给", allowance: "津贴；补贴",
      alternative: "替代的；选择方案", ambassador: "大使；使者", amendment: "修改；修正",
      analysis: "分析；解析", announce: "宣布；通告", annual: "年度的；每年的",
      anticipate: "预期；期望", applicant: "申请人；求职者", application: "申请；应用",
      appoint: "任命；指定", appraisal: "评价；评估", appreciate: "欣赏；升值",
      approach: "方法；接近", appropriate: "适当的；合适的", approval: "批准；认可",
      asset: "资产", assign: "分配；指派", assistance: "帮助；协助",
      associate: "联合；关联", assume: "假设；承担", assurance: "保证；保险",
      auction: "拍卖", audit: "审计；查账", authority: "权威；权力",
      authorize: "授权；批准", average: "平均的；普通的", award: "奖；奖品",
      backer: "支持者；赞助人", backlog: "积压的工作；订单", balance: "平衡；余额",
      bank: "银行；河岸", bankruptcy: "破产；倒闭", bargain: "讨价还价；便宜货",
      barrier: "障碍物；壁垒", batch: "一批；成批", behalf: "代表；利益",
      benefit: "利益；好处", bid: "出价；投标", billion: "十亿",
      board: "董事会；板", bond: "债券；联系", bonus: "奖金；红利",
      bookkeeping: "簿记；记账", boom: "繁荣；暴涨", boost: "促进；提高",
      brand: "品牌；商标", breach: "违反；违背", breakthrough: "突破；重大发现",
      bribe: "贿赂", broker: "经纪人；中间人", budget: "预算",
      bureau: "局；办事处", business: "商业；生意", calculate: "计算；估计",
      campaign: "运动；战役", cancellation: "取消；注销", candidate: "候选人",
      capacity: "容量；能力", capital: "资本；首都", career: "事业；生涯",
      cargo: "货物；船货", cash: "现金；现款", catalog: "目录；产品目录",
      category: "类别；种类", centralized: "集中化的；中央集权的", certificate: "证书；执照",
      chair: "主席；椅子", chamber: "会议室；腔", change: "改变；变化",
      channel: "渠道；通道", chariman: "主席；董事长", charge: "收费；指控；充电",
      charter: "章程；包租", check: "检查；支票", claim: "索赔；声称",
      clause: "条款；从句", clear: "清楚的；清算", client: "客户；委托人",
      code: "代码；法规", collaborate: "合作；协作", collateral: "抵押品；担保品",
      colleague: "同事；同僚", collect: "收集；收款", commerce: "商业；贸易",
      commission: "委员会；佣金", commitment: "承诺；承担义务", commodity: "商品；货物",
      communication: "通讯；交流", company: "公司；陪伴", compensation: "赔偿；补偿",
      compete: "竞争；比赛", competence: "能力；胜任", competition: "竞争；比赛",
      competitor: "竞争者；对手", complaint: "投诉；抱怨", complete: "完整的；完成",
      compliance: "合规；遵从", component: "成分；组件", composition: "组成；作文",
      compound: "化合物；复合的", comprehensive: "全面的；综合的", compromise: "妥协；折中",
      conference: "会议；讨论会", confidence: "信心；信任", confirm: "确认；证实",
      conflict: "冲突；矛盾", conglomerate: "企业集团；联合公司", connection: "连接；联系",
      consequence: "后果；结果", conservation: "保存；保护", consider: "考虑；认为",
      consideration: "考虑；补偿", consist: "由...组成", consolidate: "巩固；合并",
      consortium: "财团；联合体", constant: "不变的；持续的", constituent: "成分；选民",
      constitute: "构成；组成", construct: "建造；构建", consultant: "顾问",
      consume: "消费；消耗", consumer: "消费者；顾客", contact: "联系；接触",
      container: "容器；集装箱", contract: "合同；收缩", contribute: "贡献；捐献",
      contribution: "贡献；捐献", control: "控制；管理", controversy: "争论；争议",
      convenience: "便利；方便", convention: "惯例；大会", convert: "转换；改变",
      convey: "传达；运送", cooperate: "合作；协作", coordination: "协调；协同",
      copyright: "版权；著作权", core: "核心；中心", corporate: "公司的；法人的",
      corporation: "公司；企业", correct: "正确的；纠正", correlation: "相关；关联",
      correspondence: "通信；信件；对应", cost: "成本；花费", council: "委员会；理事会",
      counsel: "律师；法律顾问；建议", count: "计数；计算", counter: "柜台；反对",
      counterfeit: "假冒的；伪造的", counterpart: "对应的人或物", coupon: "优惠券；息票",
      create: "创造；创建", creative: "有创造力的", credibility: "可信性；信誉",
      credit: "信用；信贷；学分", crisis: "危机；紧要关头", criteria: "标准；准则",
      critical: "关键的；批评的", culture: "文化；企业文化", currency: "货币；流通",
      current: "当前的；水流", customer: "顾客；客户", cycle: "循环；周期",
      damage: "损害；损失", deadline: "截止日期；最后期限", deal: "交易；处理",
      debate: "辩论；争论", debt: "债务；欠款", decade: "十年；十年期",
      decide: "决定；判决", decision: "决定；决策", declaration: "声明；申报",
      decline: "下降；拒绝", decrease: "减少；减小", deduct: "扣除；减去",
      default: "违约；默认值", defeat: "击败；失败", defend: "辩护；防御",
      deficit: "赤字；亏损", define: "定义；界定", definite: "明确的；确定的",
      definition: "定义；释义", degree: "程度；学位", delay: "推迟；延误",
      delegate: "代表；授权", delete: "删除；消去", deliberate: "故意的；深思熟虑的",
      demand: "需求；要求", demonstrate: "证明；演示", denial: "否认；拒绝",
      department: "部门；系", departure: "离开；出发", depend: "依赖；依靠",
      deposit: "存款；押金；沉淀", depreciate: "贬值；折旧", deputy: "副手；代理人",
      derive: "得自；源自", describe: "描述；形容", deserve: "值得；应得",
      designate: "指定；任命", desire: "渴望；期望", destination: "目的地；终点",
      destroy: "破坏；毁灭", detail: "细节；详情", detection: "探测；察觉",
      determination: "决心；决定", develop: "发展；开发", device: "设备；装置",
      differentiate: "区分；使不同", diminish: "减少；减小", director: "主任；董事"
    }
  }
};

// === 生成器 ===
const libraryFiles = ["cet4","cet6","ielts","toefl","gre","gaokao","business"];
const levelMap = { cet4: 1, cet6: 2, ielts: 2, toefl: 3, gre: 3, gaokao: 1, business: 2 };

for (const libId of libraryFiles) {
  const data = WORD_LISTS[libId];
  if (!data) continue;
  const words = Object.keys(data.meanings);
  // 分割到 3 个等级
  const perLevel = Math.ceil(words.length / 3);
  const result = { 1: [], 2: [], 3: [] };
  words.forEach((word, idx) => {
    const level = idx < perLevel ? 1 : idx < perLevel * 2 ? 2 : 3;
    const meaning = data.meanings[word];
    result[level].push({
      word,
      meaning,
      example: `"${word}" is used in context.`,
      example_zh: `"${word}" 用于语境中。`
    });
  });
  const total = result[1].length + result[2].length + result[3].length;
  const outPath = path + libId + ".json";
  fs.writeFileSync(outPath, JSON.stringify(result, null, 2) + "\n", "utf8");
  console.log(`✅ ${libId}.json 生成完毕 (${total} 词, Lv.1=${result[1].length} Lv.2=${result[2].length} Lv.3=${result[3].length})`);
}

console.log("\n🎉 全部词库生成完成！");
